### ISSUE TITLE
New game when ?

### ISSUE THREAD

**Issue by TheIntelloBox** [NiklasEi/GameBox#18]

**Comment by TheIntelloBox** [comment]
Fantastic. :) What will be the new game, and when you think ?

**Comment by NiklasEi** [comment]
Maybe March/April. Not sure, since I'll start my master thesis around that time... Maybe I'll finish GameBox v2 first, or I'll already do a new game in Feb, who knows ^^ I am not really planing these things.

The list of Games to come is pretty long at the moment. I'd like something along "Fruit ninja" or "Mastermind" the most or a bunch of very small games (Tic-Tac-Toe, Rock Paper Scissors, Heads or tails).
