### ISSUE TITLE
GameBox 1.5.3 does not work in 1.8.9

### ISSUE THREAD

**Issue by I2000C** [NiklasEi/GameBox#3]
Hello Nikl,
I've opened this issue to get in touch with you to talk about a problem that has happened to me today with the "GameBox" plugin.
First, your plugin is amazing, because I have played it in other versions and it was very cool. But, today I installed the plugin "Battleship" and it asked me to update the "GameBox" plugin to the latest version, so today I downloaded the latest version. When I start the server, it does not load the plugin and it gives me a huge error. Please, I ask you to get it fixed as soon as possible. Thank you!
![image 1](https://user-images.githubusercontent.com/29607352/27393722-57efe200-56aa-11e7-8969-4b0b101125db.jpg)

And sorry if my English is so bad, I'm Spanish :)

**Comment by NiklasEi** [comment]
Yes, this is an issue for the older versions of 1.8, since there was a character limit for inventory titles. I use Spigot 1.8, Spigot 1.8.3 and Spigot 1.8.8 for testing and the bug disappears for version 1.8.8. I've never heard about a version 1.8.9.

The only fix for older 1.8 versions would be to go through all the language files and shorten all inventory titles to less then 32 characters. If you want enough information in your titles, this leads to not being able to use colorcodes (that is why all the default titles are longer then 32 characters).

There shouldn't be any problem when using Spigot 1.8.8.

**Comment by I2000C** [comment]
Thank you very much. 
I will try to reduce all text to less than 32 characters. 
I'll tell you soon if this solves the issue. Bye

**Comment by NiklasEi** [comment]
I would suggest using Spigot 1.8.8 instead. Keeping the titles short is a restriction and there shouldn't be a problem with simply changing to 1.8.8, is there?

**Comment by I2000C** [comment]
I have tried to put the server in version 1.8.8, but the issue continued. Then, I've tried reducing the text in the "TITLES" section of the language file. And after that, it was no longer an error. I was starting to get very happy. Until that, I put the battleship plugin to test it at last and it will not let me place the boats. This is the error that occurs every time I click on the water:
![image 2](https://user-images.githubusercontent.com/29607352/27408289-33f6370a-56dc-11e7-8295-e4d23113ce5e.jpg)

**Comment by NiklasEi** [comment]
You are not using Spigot. CraftBukkit?

I can fix that issue, no problem. Thanks for reporting it.

**Comment by NiklasEi** [comment]
Please update battleship: [Update notes](https://www.spigotmc.org/resources/battleship-%E2%9A%93-for-gamebox.26627/update?update=169698)

**Comment by I2000C** [comment]
Thank you very very much. You are the best!!! 👍
