### ISSUE TITLE
Add an option to keep armor on, when in GameBox or game gui

### ISSUE THREAD

**Issue by Zefferis** [NiklasEi/GameBox#5]
Playing games removes a player's armor.  It requires a player to move their now 'empty' armor slow away for their armor to re-appear.

If this is a configuration problem; then I'd love to know what was mis-configured.

(Noticed because we run a seasons plugin that causes players to get hurt if they don't have armor on, making minigames unplayable during our winter season)

**Comment by NiklasEi** [comment]
As soon as you start a game your inventory is emptied and that includes your armor, yes. That is not a bug I am doing this on purpose. As for the inventory: I need the space for buttons and games. Removing the armor at the same time was simply easier at the beginning and later on I kept doing it because I like the idea that players get vulnerable when playing a game.

>  It requires a player to move their now 'empty' armor slow away for their armor to re-appear.
I don't understand what you mean with that. Could you elaborate?

Your problem makes sense and I will add an option to the configuration file to not remove the armor. Then the games will be playable in combination with your seasons plugin.

Note: the next update may take some time as I am in my exam-period at the moment.

**Comment by NiklasEi** [comment]
That just took me alot longer than I expected. There was some old code, that was overwriting the armor without me knowing it and it took a long time to find that.

I tested with the oldest and newest minecraft version and it works fine now. It will be in the next update.
